openapi: 3.0.3
info:
  title: Ex-Module
  description: |
    # Introduction
    This API is documented in **OpenAPI format**, You can find more information :

    - **Specs:** https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#pathsObject
    - **Basic Structure:** https://swagger.io/docs/specification/basic-structure/
    - **Tutorial:** https://support.smartbear.com/swaggerhub/docs/tutorials/openapi-3-tutorial.html
    
    # Cross-Origin Resource Sharing
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with  [W3C spec](https://www.w3.org/TR/cors/).
    And that allows cross-domain communication from the browser.
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    # Authentication
    Ex-Module offers two forms of authentication:
      - Local Authentication
      - Json Web Token
  x-logo:
    url: http://localhost:3000/assets/logo.png
    altText: Ex-Module logo
  contact:
    name: API Support
    email: martiendt@gmail.com
    url: https://github.com/Redocly/redoc
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 0.0.1
servers:
  - url: https://api.ex-module.com/v1
    description: Sandbox Server
  - url: https://sandbox.ex-module.com/v1
    description: Production Server
tags:
  - name: Admin
    description: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  - name: Invoice
    description: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
  - name: Fixed Asset Group
    description: Manage Master Fixed Asset Data.
  - name: Fixed Asset
    description: Manage Master Fixed Asset Group Data.
  - name: Cut Off
    description: |
      - Problem Awal : Admin Accounting Bertugas melakukan pencatatan setiap transaksi perusahaan. Kemudian perusahaan menggunakan sistem untuk mengotomatis pencatatan transaksi perusahaan. akan tetapi admin accounting tidak bisa menambahkan saldo awal perusahaan. sehingga pembukuan harus dicatat dua kali. menggunakan excel dan menggunakan program accounting.
      - Solusi : Agar Admin accounting bisa melakukan pencatatan transaksi satu kali dan menyimpan data saldo awal perusahaan maka admin memerlukan Modul "CUT OFF" untuk memindahkan saldo awal perusahaan, menyampaikan laporan keuangan secara akurat kepada atasannya.
  
paths:
  /admins:
    $ref: './admin.yml'

  # Fixed Asset
  /api/v1/master/fixed-assets:
    $ref: './modules/master/fixed asset/fixed-asset.yml'
  /api/v1/master/fixed-assets/{id}:
    $ref: './modules/master/fixed asset/fixed-asset-id.yml'
  /api/v1/master/fixed-asset-groups:
    $ref: './modules/master/fixed asset group/fixed-asset-group.yml'
  /api/v1/master/fixed-asset-groups/{id}:
    $ref: './modules/master/fixed asset group/fixed-asset-group-id.yml'

  # Cutoff
  /api/v1/accounting/cut-offs:
    $ref: './modules/accounting/cutoff/cut-off.yml'
  /api/v1/accounting/cut-offs/account:
    $ref: './modules/accounting/cutoff/cut-off-account.yml'
  /api/v1/accounting/cut-offs/account/{id}:
    $ref: './modules/accounting/cutoff/cut-off-account-id.yml'
  /api/v1/accounting/cut-offs/total:
    $ref: './modules/accounting/cutoff/cut-off-total.yml'